# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin
trigger:
- main

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'PerfectBody-Deployment'
    appSlug: 'santhosh.kannan-aspiresys.com/Demo-PerfectBody'
    appFile: '$(System.DefaultWorkingDirectory)/_Demo-Xamarian-Android-Xamarin.Android-CI (1)/drop/Perfect_Body.Perfect_Body.apk'
    releaseNotesOption: 'input'
    releaseNotesInput: 'DEploy'
    destinationType: 'groups'
    distributionGroupId: '64620b41-6e2a-429e-baa8-b6a130350730'